export const dari = {
  common: {
    continue: 'ادامه',
    cancel: 'لغو',
    save: 'ذخیره',
    delete: 'حذف',
    edit: 'ویرایش',
    back: 'برگشت',
    next: 'بعدی',
    submit: 'ارسال',
    confirm: 'تایید',
    close: 'بستن',
    search: 'جستجو',
    filter: 'فیلتر',
    apply: 'اعمال',
    reset: 'بازنشانی',
    select: 'انتخاب',
    loading: 'در حال بارگذاری...',
    error: 'خطا',
    success: 'موفقیت',
    yes: 'بله',
    no: 'خیر',
    ok: 'باشه',
    done: 'تمام',
    required: 'ضروری',
    optional: 'اختیاری',
    all: 'همه',
    more: 'بیشتر',
    less: 'کمتر',
    viewAll: 'مشاهده همه',
    language: 'زبان',
    changeLanguage: 'تغییر زبان',
  },
  auth: {
    login: 'ورود',
    register: 'ثبت نام',
    logout: 'خروج',
    forgotPassword: 'رمز عبور را فراموش کرده اید؟',
    resetPassword: 'بازنشانی رمز عبور',
    email: 'ایمیل',
    password: 'رمز عبور',
    confirmPassword: 'تایید رمز عبور',
    fullName: 'نام کامل',
    phone: 'شماره تماس',
    username: 'نام کاربری',
    welcomeBack: 'خوش آمدید',
    createAccount: 'ایجاد حساب کاربری',
    alreadyHaveAccount: 'حساب کاربری دارید؟',
    dontHaveAccount: 'حساب کاربری ندارید؟',
    signIn: 'ورود',
    signUp: 'ثبت نام',
    enterEmail: 'ایمیل خود را وارد کنید',
    enterPassword: 'رمز عبور خود را وارد کنید',
    enterPhone: 'شماره تماس خود را وارد کنید',
    enterOTP: 'کد تایید را وارد کنید',
    verifyOTP: 'تایید کد',
    resendOTP: 'ارسال مجدد کد',
    otpSent: 'کد تایید ارسال شد',
    invalidCredentials: 'اطلاعات نامعتبر',
    rememberMe: 'مرا به خاطر بسپار',
  },
  tabs: {
    home: 'خانه',
    dashboard: 'داشبورد',
    properties: 'املاک',
    filters: 'فیلترها',
    reset: 'بازنشانی',
    people: 'افراد',
    profile: 'پروفایل',
    menus: 'منو',
    add: 'افزودن',
    createProperty: 'افزودن ملک',
    insights: 'گزارشات',
  },
  welcome: {
    badge: 'آدرس بعدی‌تان را پیدا کنید',
    title: 'املاک مطمئن برای تصمیم‌گیری سریع',
    subtitle: 'فهرست‌های ویژه، پروژه‌ها و مشاوران تاییدشده را یکجا و آسان ببینید.',
    feature1Title: 'جستجوی هوشمند ملک',
    feature1Subtitle: 'بر اساس موقعیت، بودجه و نوع ملک سریع فیلتر کنید.',
    feature2Title: 'پروژه‌ها و شهرک‌ها',
    feature2Subtitle: 'برج‌ها، بازارها و شهرک‌ها را با موجودی واقعی واحدها ببینید.',
    feature3Title: 'ارتباطات تاییدشده',
    feature3Subtitle: 'مستقیم با مشاوران معتبر تماس بگیرید و با اطمینان پیش بروید.',
    getStarted: 'شروع جستجو',
    signIn: 'ورود',
    exploreGuest: 'جستجو به‌عنوان مهمان',
  },
  property: {
    property: 'ملک',
    properties: 'املاک',
    myProperties: 'املاک من',
    addProperty: 'افزودن ملک',
    editProperty: 'ویرایش ملک',
    deleteProperty: 'حذف ملک',
    propertyDetails: 'جزئیات ملک',
    propertyType: 'نوع ملک',
    price: 'قیمت',
    location: 'موقعیت',
    area: 'مساحت',
    bedrooms: 'اتاق خواب',
    bathrooms: 'حمام',
    beds: 'خواب',
    baths: 'حمام',
    sqft: 'متر مربع',
    forSale: 'برای فروش',
    forRent: 'برای اجاره',
    sale: 'فروش',
    rent: 'اجاره',
    sold: 'فروخته شده',
    rented: 'اجاره داده شده',
    available: 'موجود',
    unavailable: 'ناموجود',
    featured: 'ویژه',
    new: 'جدید',
    popular: 'محبوب',
    recommended: 'پیشنهادی',
    nearby: 'نزدیک',
    viewProperty: 'مشاهده ملک',
    contactAgent: 'تماس با مشاور',
    shareProperty: 'اشتراک گذاری ملک',
    saveProperty: 'ذخیره ملک',
    favorites: 'علاقه‌مندی‌ها',
    noProperties: 'ملکی یافت نشد',
    house: 'خانه',
    apartment: 'آپارتمان',
    shop: 'دکان',
    office: 'دفتر',
    land: 'زمین',
    plot: 'قطعه',
    tower: 'برج',
    towers: 'برج‌ها',
    market: 'بازار',
    markets: 'بازارها',
    sharak: 'شهرک',
    sharaks: 'شهرک‌ها',
    building: 'ساختمان',
    units: 'واحد',
    floor: 'طبقه',
    unitNumber: 'شماره واحد',
    totalFloors: 'تعداد طبقات',
    amenities: 'امکانات',
    description: 'توضیحات',
    title: 'عنوان',
    address: 'آدرس',
    priceOnRequest: 'قیمت بر اساس توافق',
    parking: 'پارکینگ',
    securityGuard: 'نگهبان امنیتی',
    centralHeatingSystem: 'سیستم گرمایش مرکزی',
    cupboards: 'کمد دیواری',
    sunny: 'آفتاب گیر',
    basement: 'زیرزمین',
    ac: 'تهویه مطبوع',
    lift: 'آسانسور',
    furnished: 'مبله',
    semiFurnished: 'نیمه مبله',
    solarFacility: 'امکانات خورشیدی',
    generatorFacility: 'امکانات برق اضطراری',
    electricity: 'برق',
    waterSupply: 'آبرسانی',
    internet: 'اینترنت',
    gym: 'باشگاه ورزشی',
    pool: 'استخر',
    garden: 'باغچه',
    gas: 'گاز',
    perMonth: '/ ماه',
    active: 'فعال',
    deActive: 'غیرفعال',
    planned: 'برنامه ریزی شده',
    added: 'اضافه شده',
    locatedIn: 'واقع در',
    verifiedAgent: 'مشاور تایید شده',
    propertyOwner: 'مالک ملک',
    sqFt: 'متر مربع',
    bath: 'حمام',
    bed: 'خواب',
    unitsAvailableIn: 'واحدهای موجود در این',
    container: 'کانتینر',
    addUnit: 'افزودن واحد',
    noHomesAvailable: 'هنوز خانه ای موجود نیست',
    propertyDescription: 'توضیحات ملک',
    openInMaps: 'باز کردن در نقشه',
    tapToExpand: 'برای بزرگنمایی کلیک کنید',
    mapNotAvailable: 'موقعیت نقشه موجود نیست',
    propertyInformation: 'اطلاعات ملک',
    propertyCode: 'کد ملک',
    ownerName: 'نام مالک',
    copied: 'کپی شد',
    propertyCodeCopied: 'کد ملک {code} در کلیپ بورد کپی شد',
    deletePropertyTitle: 'حذف ملک',
    deletePropertyMessage: 'این اقدام قابل بازگشت نیست. آیا مطمئن هستید؟',
    failedToDelete: 'حذف ملک ناموفق بود',
    propertyNotFound: 'ملک یافت نشد',
    returnToBrowse: 'بازگشت به مرور',
    transaction: 'معامله',
    sendInquiry: 'ارسال درخواست',
    inquirySent: 'درخواست ارسال شد',
    inquiryRecorded: 'علاقه شما به این ملک ثبت شد.',
    whatsappNotInstalled: 'واتساپ در دستگاه شما نصب نیست',
    unableToOpenVideo: 'امکان باز کردن این ویدیو وجود ندارد',
    locationNotSpecified: 'موقعیت مشخص نشده است',
    shopNo: 'شماره دکان',
    officeNo: 'شماره دفتر',
    apartmentNo: 'شماره آپارتمان',
    featuresTab: 'ویژگی‌ها',
    availableHomes: 'خانه‌های موجود',
    allProperties: 'همه املاک',
    about: 'درباره',
    noDescriptionAvailable: 'توضیحات موجود نیست.',
    facilities: 'امکانات',
    agentInformation: 'اطلاعات مشاور',
    tapToViewProfile: 'برای دیدن پروفایل لمس کنید',
    showing: 'نمایش',
    availableHomesLower: 'خانه‌های موجود',
    propertiesAddedByAgent: 'املاک افزوده‌شده توسط مشاور',
    propertyTypeUpper: 'نوع ملک',
    bedroomsUpper: 'اتاق خواب',
    allBeds: 'همه اتاق‌ها',
    others: 'سایر',
    noAvailableHomesFound: 'هیچ خانه موجودی یافت نشد.',
    noPropertiesAddedByAgent: 'هنوز ملکی توسط این مشاور افزوده نشده است.',
    addShopOffice: 'افزودن دکان/دفتر',
    addApartmentShopOfficeLandPlotHouse: 'افزودن آپارتمان/دکان/دفتر/زمین/قطعه/خانه',
    addApartmentShopOffice: 'افزودن آپارتمان/دکان/دفتر',
  },
  filters: {
    filters: 'فیلترها',
    applyFilters: 'اعمال فیلترها',
    clearFilters: 'پاک کردن فیلترها',
    propertyType: 'نوع ملک',
    priceRange: 'محدوده قیمت',
    minPrice: 'حداقل قیمت',
    maxPrice: 'حداکثر قیمت',
    min: 'حداقل',
    max: 'حداکثر',
    location: 'موقعیت',
    bedrooms: 'اتاق خواب',
    bathrooms: 'حمام',
    area: 'مساحت',
    status: 'وضعیت',
    sortBy: 'مرتب سازی',
    newest: 'جدیدترین',
    oldest: 'قدیمی‌ترین',
    priceLowToHigh: 'قیمت: کم به زیاد',
    priceHighToLow: 'قیمت: زیاد به کم',
    province: 'ولایت',
    district: 'ولسوالی',
    districtIn: 'ولسوالی در',
    areaLocation: 'ناحیه',
    areaIn: 'ناحیه در',
    category: 'دسته بندی',
    purpose: 'هدف',
    agent: 'مشاور',
    priceRangeRent: 'محدوده قیمت (اجاره)',
    priceRangeSale: 'محدوده قیمت (فروش)',
    searching: 'در حال جستجو...',
    searchProperties: 'جستجوی املاک',
  },
  profile: {
    profile: 'پروفایل',
    myProfile: 'پروفایل من',
    editProfile: 'ویرایش پروفایل',
    myTowers: 'برج‌های من',
    myMarkets: 'بازارهای من',
    mySharaks: 'شهرک‌های من',
    settings: 'تنظیمات',
    help: 'کمک',
    about: 'درباره',
    termsAndConditions: 'شرایط و ضوابط',
    privacyPolicy: 'سیاست حفظ حریم خصوصی',
    contactUs: 'تماس با ما',
    rateApp: 'امتیاز دهی به اپلیکیشن',
    shareApp: 'اشتراک گذاری اپلیکیشن',
    version: 'نسخه',
    accountSettings: 'تنظیمات حساب کاربری',
    notifications: 'اعلان‌ها',
    language: 'زبان',
    darkMode: 'حالت تاریک',
    myFavorites: 'علاقه‌مندی‌های من',
    savedSearches: 'جستجوهای ذخیره شده',
    recentlyViewed: 'اخیراً مشاهده شده',
  },
  dashboard: {
    welcome: 'خوش آمدید',
    hello: 'سلام',
    recentProperties: 'املاک اخیر',
    featuredProperties: 'املاک ویژه',
    popularProperties: 'املاک محبوب',
    stats: 'آمار',
    totalProperties: 'مجموع املاک',
    totalAgents: 'مجموع مشاوران',
    totalDeals: 'مجموع معاملات',
    quickActions: 'اقدامات سریع',
    adminConsole: 'کنسول ادمین',
    systemStatus: 'وضعیت سیستم: فعال',
    users: 'کاربران',
    agents: 'مشاوران',
    globalStatistics: 'آمار عمومی',
    activeDeals: 'معاملات فعال',
    managementTools: 'ابزارهای مدیریت',
    rolesPermissions: 'نقش‌ها و مجوزها',
    reviewAllListings: 'بررسی تمام لیست‌ها',
    analyzeGrowth: 'تحلیل رشد',
    systemPlatform: 'پلتفرم سیستم',
    towers: 'برج‌های چشم‌انداز',
    markets: 'بازارهای پررونق',
    sharaks: 'شهرک‌های لوکس',
    loadingContent: 'در حال بارگذاری محتوا...',
    signInPrompt: 'به حساب کاربری املاک خود وارد شوید',
  },
  people: {
    people: 'افراد',
    agents: 'مشاوران',
    owners: 'مالکان',
    clients: 'مشتریان',
    contactInfo: 'اطلاعات تماس',
    propertiesListed: 'املاک ثبت شده',
    viewProfile: 'مشاهده پروفایل',
  },
  deals: {
    deals: 'معاملات',
    myDeals: 'معاملات من',
    createDeal: 'ایجاد معامله',
    viewDeal: 'مشاهده معامله',
    dealDetails: 'جزئیات معامله',
    dealStatus: 'وضعیت معامله',
    pending: 'در انتظار',
    active: 'فعال',
    completed: 'تکمیل شده',
    cancelled: 'لغو شده',
  },
  errors: {
    somethingWentWrong: 'مشکلی پیش آمد',
    tryAgain: 'دوباره تلاش کنید',
    networkError: 'خطای شبکه',
    invalidInput: 'ورودی نامعتبر',
    requiredField: 'این فیلد الزامی است',
    invalidEmail: 'آدرس ایمیل نامعتبر',
    invalidPhone: 'شماره تماس نامعتبر',
    passwordTooShort: 'رمز عبور خیلی کوتاه است',
    passwordValid: 'رمز عبور شرایط لازم را دارد',
    passwordsMatch: 'رمزهای عبور مطابقت دارند',
    passwordsDoNotMatch: 'رمز عبور مطابقت ندارد',
  },
  success: {
    propertySaved: 'ملک با موفقیت ذخیره شد',
    propertyDeleted: 'ملک با موفقیت حذف شد',
    propertyUpdated: 'ملک با موفقیت به‌روزرسانی شد',
    profileUpdated: 'پروفایل با موفقیت به‌روزرسانی شد',
    settingsSaved: 'تنظیمات با موفقیت ذخیره شد',
  },
};
