export const dari = {
  common: {
    continue: 'ادامه',
    cancel: 'لغو',
    save: 'ذخیره',
    delete: 'حذف',
    edit: 'ویرایش',
    back: 'برگشت',
    next: 'بعدی',
    submit: 'ارسال',
    confirm: 'تایید',
    close: 'بستن',
    search: 'جستجو',
    filter: 'فیلتر',
    apply: 'اعمال',
    reset: 'بازنشانی',
    select: 'انتخاب',
    loading: 'در حال بارگذاری...',
    error: 'خطا',
    success: 'موفقیت',
    yes: 'بله',
    no: 'خیر',
    ok: 'باشه',
    done: 'تمام',
    required: 'ضروری',
    optional: 'اختیاری',
    all: 'همه',
    more: 'بیشتر',
    less: 'کمتر',
    viewAll: 'مشاهده همه',
    language: 'زبان',
    changeLanguage: 'تغییر زبان',
  },
  auth: {
    login: 'ورود',
    register: 'ثبت نام',
    logout: 'خروج',
    forgotPassword: 'رمز عبور را فراموش کرده اید؟',
    resetPassword: 'بازنشانی رمز عبور',
    email: 'ایمیل',
    password: 'رمز عبور',
    confirmPassword: 'تایید رمز عبور',
    fullName: 'نام کامل',
    phone: 'شماره تماس',
    username: 'نام کاربری',
    welcomeBack: 'خوش آمدید',
    createAccount: 'ایجاد حساب کاربری',
    alreadyHaveAccount: 'حساب کاربری دارید؟',
    dontHaveAccount: 'حساب کاربری ندارید؟',
    signIn: 'ورود',
    signUp: 'ثبت نام',
    enterEmail: 'ایمیل خود را وارد کنید',
    enterPassword: 'رمز عبور خود را وارد کنید',
    enterPhone: 'شماره تماس خود را وارد کنید',
    enterOTP: 'کد تایید را وارد کنید',
    verifyOTP: 'تایید کد',
    resendOTP: 'ارسال مجدد کد',
    otpSent: 'کد تایید ارسال شد',
    invalidCredentials: 'اطلاعات نامعتبر',
    rememberMe: 'مرا به خاطر بسپار',
  },
  tabs: {
    dashboard: 'داشبورد',
    properties: 'املاک',
    filters: 'فیلترها',
    people: 'افراد',
    profile: 'پروفایل',
    menus: 'منو',
    createProperty: 'افزودن ملک',
    insights: 'گزارشات',
  },
  property: {
    property: 'ملک',
    properties: 'املاک',
    myProperties: 'املاک من',
    addProperty: 'افزودن ملک',
    editProperty: 'ویرایش ملک',
    deleteProperty: 'حذف ملک',
    propertyDetails: 'جزئیات ملک',
    propertyType: 'نوع ملک',
    price: 'قیمت',
    location: 'موقعیت',
    area: 'مساحت',
    bedrooms: 'اتاق خواب',
    bathrooms: 'حمام',
    beds: 'خواب',
    baths: 'حمام',
    sqft: 'متر مربع',
    forSale: 'برای فروش',
    forRent: 'برای اجاره',
    sale: 'فروش',
    rent: 'اجاره',
    sold: 'فروخته شده',
    rented: 'اجاره داده شده',
    available: 'موجود',
    unavailable: 'ناموجود',
    featured: 'ویژه',
    new: 'جدید',
    popular: 'محبوب',
    recommended: 'پیشنهادی',
    nearby: 'نزدیک',
    viewProperty: 'مشاهده ملک',
    contactAgent: 'تماس با مشاور',
    shareProperty: 'اشتراک گذاری ملک',
    saveProperty: 'ذخیره ملک',
    favorites: 'علاقه‌مندی‌ها',
    noProperties: 'ملکی یافت نشد',
    house: 'خانه',
    apartment: 'آپارتمان',
    shop: 'دکان',
    office: 'دفتر',
    land: 'زمین',
    plot: 'قطعه',
    tower: 'برج',
    market: 'بازار',
    sharak: 'شهرک',
    building: 'ساختمان',
    units: 'واحد',
    floor: 'طبقه',
    unitNumber: 'شماره واحد',
    totalFloors: 'تعداد طبقات',
    amenities: 'امکانات',
    description: 'توضیحات',
    title: 'عنوان',
    address: 'آدرس',
    priceOnRequest: 'قیمت بر اساس توافق',
  },
  filters: {
    filters: 'فیلترها',
    applyFilters: 'اعمال فیلترها',
    clearFilters: 'پاک کردن فیلترها',
    propertyType: 'نوع ملک',
    priceRange: 'محدوده قیمت',
    minPrice: 'حداقل قیمت',
    maxPrice: 'حداکثر قیمت',
    location: 'موقعیت',
    bedrooms: 'اتاق خواب',
    bathrooms: 'حمام',
    area: 'مساحت',
    status: 'وضعیت',
    sortBy: 'مرتب سازی',
    newest: 'جدیدترین',
    oldest: 'قدیمی‌ترین',
    priceLowToHigh: 'قیمت: کم به زیاد',
    priceHighToLow: 'قیمت: زیاد به کم',
    province: 'ولایت',
    district: 'ولسوالی',
    areaLocation: 'ناحیه',
  },
  profile: {
    profile: 'پروفایل',
    myProfile: 'پروفایل من',
    editProfile: 'ویرایش پروفایل',
    settings: 'تنظیمات',
    help: 'کمک',
    about: 'درباره',
    termsAndConditions: 'شرایط و ضوابط',
    privacyPolicy: 'سیاست حفظ حریم خصوصی',
    contactUs: 'تماس با ما',
    rateApp: 'امتیاز دهی به اپلیکیشن',
    shareApp: 'اشتراک گذاری اپلیکیشن',
    version: 'نسخه',
    accountSettings: 'تنظیمات حساب کاربری',
    notifications: 'اعلان‌ها',
    language: 'زبان',
    darkMode: 'حالت تاریک',
    myFavorites: 'علاقه‌مندی‌های من',
    savedSearches: 'جستجوهای ذخیره شده',
    recentlyViewed: 'اخیراً مشاهده شده',
  },
  dashboard: {
    welcome: 'خوش آمدید',
    hello: 'سلام',
    recentProperties: 'املاک اخیر',
    featuredProperties: 'املاک ویژه',
    popularProperties: 'املاک محبوب',
    stats: 'آمار',
    totalProperties: 'مجموع املاک',
    totalAgents: 'مجموع مشاوران',
    totalDeals: 'مجموع معاملات',
    quickActions: 'اقدامات سریع',
  },
  people: {
    people: 'افراد',
    agents: 'مشاوران',
    owners: 'مالکان',
    clients: 'مشتریان',
    contactInfo: 'اطلاعات تماس',
    propertiesListed: 'املاک ثبت شده',
    viewProfile: 'مشاهده پروفایل',
  },
  deals: {
    deals: 'معاملات',
    myDeals: 'معاملات من',
    createDeal: 'ایجاد معامله',
    viewDeal: 'مشاهده معامله',
    dealDetails: 'جزئیات معامله',
    dealStatus: 'وضعیت معامله',
    pending: 'در انتظار',
    active: 'فعال',
    completed: 'تکمیل شده',
    cancelled: 'لغو شده',
  },
  errors: {
    somethingWentWrong: 'مشکلی پیش آمد',
    tryAgain: 'دوباره تلاش کنید',
    networkError: 'خطای شبکه',
    invalidInput: 'ورودی نامعتبر',
    requiredField: 'این فیلد الزامی است',
    invalidEmail: 'آدرس ایمیل نامعتبر',
    invalidPhone: 'شماره تماس نامعتبر',
    passwordTooShort: 'رمز عبور خیلی کوتاه است',
    passwordsDoNotMatch: 'رمز عبور مطابقت ندارد',
  },
  success: {
    propertySaved: 'ملک با موفقیت ذخیره شد',
    propertyDeleted: 'ملک با موفقیت حذف شد',
    propertyUpdated: 'ملک با موفقیت به‌روزرسانی شد',
    profileUpdated: 'پروفایل با موفقیت به‌روزرسانی شد',
    settingsSaved: 'تنظیمات با موفقیت ذخیره شد',
  },
};
