export const en = {
  common: {
    continue: 'Continue',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    confirm: 'Confirm',
    close: 'Close',
    search: 'Search',
    filter: 'Filter',
    apply: 'Apply',
    reset: 'Reset',
    select: 'Select',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    done: 'Done',
    required: 'Required',
    optional: 'Optional',
    all: 'All',
    more: 'More',
    less: 'Less',
    viewAll: 'View All',
    language: 'Language',
    changeLanguage: 'Change Language',
  },
  auth: {
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    phone: 'Phone Number',
    username: 'Username',
    welcomeBack: 'Welcome Back',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    signIn: 'Sign In',
    signUp: 'Sign Up',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    enterPhone: 'Enter your phone number',
    enterOTP: 'Enter verification code',
    verifyOTP: 'Verify Code',
    resendOTP: 'Resend Code',
    otpSent: 'Verification code sent',
    invalidCredentials: 'Invalid credentials',
    rememberMe: 'Remember me',
  },
  tabs: {
    dashboard: 'Dashboard',
    properties: 'Properties',
    filters: 'Filters',
    people: 'People',
    profile: 'Profile',
    menus: 'Menu',
    createProperty: 'Add Property',
    insights: 'Insights',
  },
  property: {
    property: 'Property',
    properties: 'Properties',
    myProperties: 'My Properties',
    addProperty: 'Add Property',
    editProperty: 'Edit Property',
    deleteProperty: 'Delete Property',
    propertyDetails: 'Property Details',
    propertyType: 'Property Type',
    price: 'Price',
    location: 'Location',
    area: 'Area',
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    beds: 'Beds',
    baths: 'Baths',
    sqft: 'sqft',
    forSale: 'For Sale',
    forRent: 'For Rent',
    sale: 'Sale',
    rent: 'Rent',
    sold: 'Sold',
    rented: 'Rented',
    available: 'Available',
    unavailable: 'Unavailable',
    featured: 'Featured',
    new: 'New',
    popular: 'Popular',
    recommended: 'Recommended',
    nearby: 'Nearby',
    viewProperty: 'View Property',
    contactAgent: 'Contact Agent',
    shareProperty: 'Share Property',
    saveProperty: 'Save Property',
    favorites: 'Favorites',
    noProperties: 'No properties found',
    house: 'House',
    apartment: 'Apartment',
    shop: 'Shop',
    office: 'Office',
    land: 'Land',
    plot: 'Plot',
    tower: 'Tower',
    market: 'Market',
    sharak: 'Sharak',
    building: 'Building',
    units: 'Units',
    floor: 'Floor',
    unitNumber: 'Unit Number',
    totalFloors: 'Total Floors',
    amenities: 'Amenities',
    description: 'Description',
    title: 'Title',
    address: 'Address',
    priceOnRequest: 'Price on Request',
  },
  filters: {
    filters: 'Filters',
    applyFilters: 'Apply Filters',
    clearFilters: 'Clear Filters',
    propertyType: 'Property Type',
    priceRange: 'Price Range',
    minPrice: 'Min Price',
    maxPrice: 'Max Price',
    location: 'Location',
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    area: 'Area Size',
    status: 'Status',
    sortBy: 'Sort By',
    newest: 'Newest',
    oldest: 'Oldest',
    priceLowToHigh: 'Price: Low to High',
    priceHighToLow: 'Price: High to Low',
    province: 'Province',
    district: 'District',
    areaLocation: 'Area',
  },
  profile: {
    profile: 'Profile',
    myProfile: 'My Profile',
    editProfile: 'Edit Profile',
    settings: 'Settings',
    help: 'Help',
    about: 'About',
    termsAndConditions: 'Terms & Conditions',
    privacyPolicy: 'Privacy Policy',
    contactUs: 'Contact Us',
    rateApp: 'Rate App',
    shareApp: 'Share App',
    version: 'Version',
    accountSettings: 'Account Settings',
    notifications: 'Notifications',
    language: 'Language',
    darkMode: 'Dark Mode',
    myFavorites: 'My Favorites',
    savedSearches: 'Saved Searches',
    recentlyViewed: 'Recently Viewed',
  },
  dashboard: {
    welcome: 'Welcome',
    hello: 'Hello',
    recentProperties: 'Recent Properties',
    featuredProperties: 'Featured Properties',
    popularProperties: 'Popular Properties',
    stats: 'Statistics',
    totalProperties: 'Total Properties',
    totalAgents: 'Total Agents',
    totalDeals: 'Total Deals',
    quickActions: 'Quick Actions',
  },
  people: {
    people: 'People',
    agents: 'Agents',
    owners: 'Owners',
    clients: 'Clients',
    contactInfo: 'Contact Info',
    propertiesListed: 'Properties Listed',
    viewProfile: 'View Profile',
  },
  deals: {
    deals: 'Deals',
    myDeals: 'My Deals',
    createDeal: 'Create Deal',
    viewDeal: 'View Deal',
    dealDetails: 'Deal Details',
    dealStatus: 'Deal Status',
    pending: 'Pending',
    active: 'Active',
    completed: 'Completed',
    cancelled: 'Cancelled',
  },
  errors: {
    somethingWentWrong: 'Something went wrong',
    tryAgain: 'Try again',
    networkError: 'Network error',
    invalidInput: 'Invalid input',
    requiredField: 'This field is required',
    invalidEmail: 'Invalid email address',
    invalidPhone: 'Invalid phone number',
    passwordTooShort: 'Password is too short',
    passwordsDoNotMatch: 'Passwords do not match',
  },
  success: {
    propertySaved: 'Property saved successfully',
    propertyDeleted: 'Property deleted successfully',
    propertyUpdated: 'Property updated successfully',
    profileUpdated: 'Profile updated successfully',
    settingsSaved: 'Settings saved successfully',
  },
};

export type TranslationKeys = typeof en;
