export const en = {
  common: {
    continue: 'Continue',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    confirm: 'Confirm',
    close: 'Close',
    search: 'Search',
    filter: 'Filter',
    apply: 'Apply',
    reset: 'Reset',
    select: 'Select',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    done: 'Done',
    required: 'Required',
    optional: 'Optional',
    all: 'All',
    more: 'More',
    less: 'Less',
    viewAll: 'View All',
    language: 'Language',
    changeLanguage: 'Change Language',
  },
  auth: {
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    phone: 'Phone Number',
    username: 'Username',
    welcomeBack: 'Welcome Back',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    signIn: 'Sign In',
    signUp: 'Sign Up',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    enterPhone: 'Enter your phone number',
    enterOTP: 'Enter verification code',
    verifyOTP: 'Verify Code',
    resendOTP: 'Resend Code',
    otpSent: 'Verification code sent',
    invalidCredentials: 'Invalid credentials',
    rememberMe: 'Remember me',
  },
  tabs: {
    home: 'Home',
    dashboard: 'Dashboard',
    properties: 'Properties',
    filters: 'Filters',
    reset: 'Reset',
    people: 'People',
    profile: 'Profile',
    menus: 'Menu',
    add: 'Add',
    createProperty: 'Add Property',
    insights: 'Insights',
  },
  welcome: {
    badge: 'Find Your Next Address',
    title: 'Trusted Real Estate, Built for Fast Decisions',
    subtitle: 'Discover premium listings, projects, and verified agents in one smooth experience.',
    feature1Title: 'Smart Property Discovery',
    feature1Subtitle: 'Filter quickly by location, budget, and property type.',
    feature2Title: 'Projects & Communities',
    feature2Subtitle: 'Explore towers, markets, and sharaks with live unit availability.',
    feature3Title: 'Verified Connections',
    feature3Subtitle: 'Contact trusted agents directly and move faster with confidence.',
    getStarted: 'Start Exploring',
    signIn: 'Sign In',
    exploreGuest: 'Explore as Guest',
  },
  property: {
    property: 'Property',
    properties: 'Properties',
    myProperties: 'My Properties',
    addProperty: 'Add Property',
    editProperty: 'Edit Property',
    deleteProperty: 'Delete Property',
    propertyDetails: 'Property Details',
    propertyType: 'Property Type',
    price: 'Price',
    location: 'Location',
    area: 'Area',
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    beds: 'Beds',
    baths: 'Baths',
    sqft: 'sqft',
    forSale: 'For Sale',
    forRent: 'For Rent',
    sale: 'Sale',
    rent: 'Rent',
    sold: 'Sold',
    rented: 'Rented',
    available: 'Available',
    unavailable: 'Unavailable',
    featured: 'Featured',
    new: 'New',
    popular: 'Popular',
    recommended: 'Recommended',
    nearby: 'Nearby',
    viewProperty: 'View Property',
    contactAgent: 'Contact Agent',
    shareProperty: 'Share Property',
    saveProperty: 'Save Property',
    favorites: 'Favorites',
    noProperties: 'No properties found',
    house: 'House',
    apartment: 'Apartment',
    shop: 'Shop',
    office: 'Office',
    land: 'Land',
    plot: 'Plot',
    tower: 'Tower',
    towers: 'Towers',
    market: 'Market',
    markets: 'Markets',
    sharak: 'Sharak',
    sharaks: 'Sharaks',
    building: 'Building',
    units: 'Units',
    floor: 'Floor',
    unitNumber: 'Unit Number',
    totalFloors: 'Total Floors',
    amenities: 'Amenities',
    description: 'Description',
    title: 'Title',
    address: 'Address',
    priceOnRequest: 'Price on Request',
    parking: 'Parking',
    securityGuard: 'Security Guard',
    centralHeatingSystem: 'Central Heating System',
    cupboards: 'Cupboards',
    sunny: 'Sunny',
    basement: 'Basement',
    ac: 'AC',
    lift: 'Lift',
    furnished: 'Furnished',
    semiFurnished: 'Semi-Furnished',
    solarFacility: 'Solar Facility',
    generatorFacility: 'Generator Facility',
    electricity: 'Electricity',
    waterSupply: 'Water Supply',
    internet: 'Internet',
    gym: 'Gym',
    pool: 'Pool',
    garden: 'Garden',
    gas: 'Gas',
    perMonth: '/ month',
    active: 'Active',
    deActive: 'De active',
    planned: 'Planned',
    added: 'Added',
    locatedIn: 'Located in',
    verifiedAgent: 'Verified Agent',
    propertyOwner: 'Property Owner',
    sqFt: 'Sq. Ft.',
    bath: 'Bath',
    bed: 'Bed',
    unitsAvailableIn: 'Units Available in This',
    container: 'Container',
    addUnit: 'Add Unit',
    noHomesAvailable: 'No homes available yet',
    propertyDescription: 'Property description',
    openInMaps: 'Open in Maps',
    tapToExpand: 'Tap to expand',
    mapNotAvailable: 'Map location not available',
    propertyInformation: 'Property Information',
    propertyCode: 'Property Code',
    ownerName: 'Owner Name',
    copied: 'Copied',
    propertyCodeCopied: 'Property code {code} copied to clipboard',
    deletePropertyTitle: 'Delete Property',
    deletePropertyMessage: 'This action cannot be undone. Are you sure?',
    failedToDelete: 'Failed to delete property',
    propertyNotFound: 'Property not found',
    returnToBrowse: 'Return to Browse',
    transaction: 'Transaction',
    sendInquiry: 'Send Inquiry',
    inquirySent: 'Inquiry Sent',
    inquiryRecorded: 'Your interest in this property has been recorded.',
    whatsappNotInstalled: 'WhatsApp is not installed on your device',
    unableToOpenVideo: 'Unable to open this video',
    locationNotSpecified: 'Location not specified',
    shopNo: 'Shop No',
    officeNo: 'Office No',
    apartmentNo: 'Apartment No',
    featuresTab: 'Features',
    availableHomes: 'Available Homes',
    allProperties: 'All Properties',
    about: 'About',
    noDescriptionAvailable: 'No description available.',
    facilities: 'Facilities',
    agentInformation: 'Agent Information',
    tapToViewProfile: 'Tap to view profile',
    showing: 'Showing',
    availableHomesLower: 'available homes',
    propertiesAddedByAgent: 'properties added by agent',
    propertyTypeUpper: 'PROPERTY TYPE',
    bedroomsUpper: 'BEDROOMS',
    allBeds: 'All Beds',
    others: 'Others',
    noAvailableHomesFound: 'No available homes found.',
    noPropertiesAddedByAgent: 'No properties added by this agent yet.',
    addShopOffice: 'Add Shop/Office',
    addApartmentShopOfficeLandPlotHouse: 'Add Apartment/Shop/Office/Land/Plot/House',
    addApartmentShopOffice: 'Add Apartment/Shop/Office',
  },
  filters: {
    filters: 'Filters',
    applyFilters: 'Apply Filters',
    clearFilters: 'Clear Filters',
    propertyType: 'Property Type',
    priceRange: 'Price Range',
    minPrice: 'Min Price',
    maxPrice: 'Max Price',
    min: 'MIN',
    max: 'MAX',
    location: 'Location',
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    area: 'Area Size',
    status: 'Status',
    sortBy: 'Sort By',
    newest: 'Newest',
    oldest: 'Oldest',
    priceLowToHigh: 'Price: Low to High',
    priceHighToLow: 'Price: High to Low',
    province: 'Province',
    district: 'District',
    districtIn: 'District in',
    areaLocation: 'Area',
    areaIn: 'Area in',
    category: 'Category',
    purpose: 'Purpose',
    agent: 'Agent',
    priceRangeRent: 'Price Range (Rent)',
    priceRangeSale: 'Price Range (Sale)',
    searching: 'Searching...',
    searchProperties: 'Search Properties',
  },
  profile: {
    profile: 'Profile',
    myProfile: 'My Profile',
    editProfile: 'Edit Profile',
    myTowers: 'My Towers',
    myMarkets: 'My Markets',
    mySharaks: 'My Sharaks',
    settings: 'Settings',
    help: 'Help',
    about: 'About',
    termsAndConditions: 'Terms & Conditions',
    privacyPolicy: 'Privacy Policy',
    contactUs: 'Contact Us',
    rateApp: 'Rate App',
    shareApp: 'Share App',
    version: 'Version',
    accountSettings: 'Account Settings',
    notifications: 'Notifications',
    language: 'Language',
    darkMode: 'Dark Mode',
    myFavorites: 'My Favorites',
    savedSearches: 'Saved Searches',
    recentlyViewed: 'Recently Viewed',
  },
  dashboard: {
    welcome: 'Welcome',
    hello: 'Hello',
    recentProperties: 'Recent Properties',
    featuredProperties: 'Featured Properties',
    popularProperties: 'Popular Properties',
    stats: 'Statistics',
    totalProperties: 'Total Properties',
    totalAgents: 'Total Agents',
    totalDeals: 'Total Deals',
    quickActions: 'Quick Actions',
    adminConsole: 'Admin Console',
    systemStatus: 'System status: Operational',
    users: 'Users',
    agents: 'Agents',
    globalStatistics: 'Global Statistics',
    activeDeals: 'Active Deals',
    managementTools: 'Management Tools',
    rolesPermissions: 'Roles & permissions',
    reviewAllListings: 'Review all listings',
    analyzeGrowth: 'Analyze growth',
    systemPlatform: 'System platform',
    towers: 'Skyline Towers',
    markets: 'Vibrant Market Hubs',
    sharaks: 'Elite Living Communities',
    loadingContent: 'Loading content...',
    signInPrompt: 'Sign in to your premium real estate account',
  },
  people: {
    people: 'People',
    agents: 'Agents',
    owners: 'Owners',
    clients: 'Clients',
    contactInfo: 'Contact Info',
    propertiesListed: 'Properties Listed',
    viewProfile: 'View Profile',
  },
  deals: {
    deals: 'Deals',
    myDeals: 'My Deals',
    createDeal: 'Create Deal',
    viewDeal: 'View Deal',
    dealDetails: 'Deal Details',
    dealStatus: 'Deal Status',
    pending: 'Pending',
    active: 'Active',
    completed: 'Completed',
    cancelled: 'Cancelled',
  },
  errors: {
    somethingWentWrong: 'Something went wrong',
    tryAgain: 'Try again',
    networkError: 'Network error',
    invalidInput: 'Invalid input',
    requiredField: 'This field is required',
    invalidEmail: 'Invalid email address',
    invalidPhone: 'Invalid phone number',
    passwordTooShort: 'Password is too short',
    passwordValid: 'Password meets the requirement',
    passwordsMatch: 'Passwords match',
    passwordsDoNotMatch: 'Passwords do not match',
  },
  success: {
    propertySaved: 'Property saved successfully',
    propertyDeleted: 'Property deleted successfully',
    propertyUpdated: 'Property updated successfully',
    profileUpdated: 'Profile updated successfully',
    settingsSaved: 'Settings saved successfully',
  },
};

export type TranslationKeys = typeof en;
