export const pashto = {
  common: {
    continue: 'دوام ورکول',
    cancel: 'لغوه کول',
    save: 'خوندي کول',
    delete: 'ړنګول',
    edit: 'سمول',
    back: 'بیرته',
    next: 'راتلونکی',
    submit: 'سپارل',
    confirm: 'تایید',
    close: 'تړل',
    search: 'لټون',
    filter: 'فلټر',
    apply: 'پلي کول',
    reset: 'بیا تنظیمول',
    select: 'غوره کول',
    loading: 'لوډ کیږي...',
    error: 'تېروتنه',
    success: 'بریالیتوب',
    yes: 'هو',
    no: 'نه',
    ok: 'سمه ده',
    done: 'بشپړ',
    required: 'اړین',
    optional: 'اختیاري',
    all: 'ټول',
    more: 'نور',
    less: 'لږ',
    viewAll: 'ټول وګورئ',
    language: 'ژبه',
    changeLanguage: 'ژبه بدلول',
  },
  auth: {
    login: 'ننوتل',
    register: 'نوم لیکنه',
    logout: 'وتل',
    forgotPassword: 'پټنوم مو هیر شوی؟',
    resetPassword: 'پټنوم بیا تنظیمول',
    email: 'برېښنالیک',
    password: 'پټنوم',
    confirmPassword: 'پټنوم تایید',
    fullName: 'بشپړ نوم',
    phone: 'تلیفون شمېره',
    username: 'کارن نوم',
    welcomeBack: 'بیرته ښه راغلاست',
    createAccount: 'حساب جوړول',
    alreadyHaveAccount: 'حساب لرئ؟',
    dontHaveAccount: 'حساب نه لرئ؟',
    signIn: 'ننوتل',
    signUp: 'نوم لیکنه',
    enterEmail: 'خپل برېښنالیک دننه کړئ',
    enterPassword: 'خپل پټنوم دننه کړئ',
    enterPhone: 'خپله تلیفون شمېره دننه کړئ',
    enterOTP: 'تایید کوډ دننه کړئ',
    verifyOTP: 'کوډ تایید',
    resendOTP: 'کوډ بیا لیږل',
    otpSent: 'تایید کوډ واستول شو',
    invalidCredentials: 'ناسم معلومات',
    rememberMe: 'ما یاد ساتئ',
  },
  tabs: {
    dashboard: 'ډشبورډ',
    properties: 'املاک',
    filters: 'فلټرونه',
    people: 'خلک',
    profile: 'پروفایل',
    menus: 'مینو',
    createProperty: 'ملک اضافه کول',
    insights: 'راپورونه',
  },
  property: {
    property: 'ملک',
    properties: 'املاک',
    myProperties: 'زما املاک',
    addProperty: 'ملک اضافه کول',
    editProperty: 'ملک سمول',
    deleteProperty: 'ملک ړنګول',
    propertyDetails: 'د ملک تفصیلات',
    propertyType: 'د ملک ډول',
    price: 'بیه',
    location: 'موقعیت',
    area: 'مساحت',
    bedrooms: 'خوب کوټې',
    bathrooms: 'تشناب',
    beds: 'خوب',
    baths: 'تشناب',
    sqft: 'مربع متر',
    forSale: 'د پلور لپاره',
    forRent: 'د کرایې لپاره',
    sale: 'پلور',
    rent: 'کرایه',
    sold: 'وپلورل شو',
    rented: 'په کرایه ورکړل شو',
    available: 'شته',
    unavailable: 'نشته',
    featured: 'ځانګړی',
    new: 'نوی',
    popular: 'مشهور',
    recommended: 'وړاندیز شوی',
    nearby: 'نږدې',
    viewProperty: 'ملک وګورئ',
    contactAgent: 'له مشاور سره اړیکه',
    shareProperty: 'ملک شریک کړئ',
    saveProperty: 'ملک خوندي کړئ',
    favorites: 'خوښې',
    noProperties: 'هیڅ ملک و نه موندل شو',
    house: 'کور',
    apartment: 'اپارتمان',
    shop: 'دکان',
    office: 'دفتر',
    land: 'ځمکه',
    plot: 'پلاټ',
    tower: 'برج',
    market: 'بازار',
    sharak: 'شهرک',
    building: 'ودانۍ',
    units: 'واحدونه',
    floor: 'پوړ',
    unitNumber: 'د واحد شمېره',
    totalFloors: 'ټول پوړونه',
    amenities: 'اسانتیاوې',
    description: 'تشریح',
    title: 'عنوان',
    address: 'پته',
    priceOnRequest: 'بیه د غوښتنې پر بنسټ',
  },
  filters: {
    filters: 'فلټرونه',
    applyFilters: 'فلټرونه پلي کول',
    clearFilters: 'فلټرونه پاکول',
    propertyType: 'د ملک ډول',
    priceRange: 'د بیې حد',
    minPrice: 'لږترلږه بیه',
    maxPrice: 'ډېره بیه',
    location: 'موقعیت',
    bedrooms: 'خوب کوټې',
    bathrooms: 'تشناب',
    area: 'مساحت',
    status: 'حالت',
    sortBy: 'ترتیبول',
    newest: 'تازه',
    oldest: 'زوړ',
    priceLowToHigh: 'بیه: ټیټه نه لوړه',
    priceHighToLow: 'بیه: لوړه نه ټیټه',
    province: 'ولایت',
    district: 'ولسوالۍ',
    areaLocation: 'ساحه',
  },
  profile: {
    profile: 'پروفایل',
    myProfile: 'زما پروفایل',
    editProfile: 'پروفایل سمول',
    settings: 'تنظیمات',
    help: 'مرسته',
    about: 'په اړه',
    termsAndConditions: 'شرایط او ضوابط',
    privacyPolicy: 'د محرمیت پالیسي',
    contactUs: 'له موږ سره اړیکه',
    rateApp: 'اپلیکیشن ته نمرې ورکړئ',
    shareApp: 'اپلیکیشن شریک کړئ',
    version: 'نسخه',
    accountSettings: 'د حساب تنظیمات',
    notifications: 'خبرتیاوې',
    language: 'ژبه',
    darkMode: 'تیاره حالت',
    myFavorites: 'زما خوښې',
    savedSearches: 'خوندي شوي لټونونه',
    recentlyViewed: 'پخوا لیدل شوي',
  },
  dashboard: {
    welcome: 'ښه راغلاست',
    hello: 'سلام',
    recentProperties: 'وروستي املاک',
    featuredProperties: 'ځانګړي املاک',
    popularProperties: 'مشهور املاک',
    stats: 'احصائیې',
    totalProperties: 'ټول املاک',
    totalAgents: 'ټول مشاورین',
    totalDeals: 'ټولې معاملې',
    quickActions: 'ګړندي اقدامات',
  },
  people: {
    people: 'خلک',
    agents: 'مشاورین',
    owners: 'مالکان',
    clients: 'پیرودونکي',
    contactInfo: 'د اړیکې معلومات',
    propertiesListed: 'ثبت شوي املاک',
    viewProfile: 'پروفایل وګورئ',
  },
  deals: {
    deals: 'معاملې',
    myDeals: 'زما معاملې',
    createDeal: 'معامله جوړول',
    viewDeal: 'معامله وګورئ',
    dealDetails: 'د معاملې تفصیلات',
    dealStatus: 'د معاملې حالت',
    pending: 'په انتظار کې',
    active: 'فعال',
    completed: 'بشپړ شوی',
    cancelled: 'لغوه شوی',
  },
  errors: {
    somethingWentWrong: 'یوه ستونزه رامنځته شوه',
    tryAgain: 'بیا هڅه وکړئ',
    networkError: 'د شبکې تېروتنه',
    invalidInput: 'ناسم معلومات',
    requiredField: 'دا برخه اړینه ده',
    invalidEmail: 'ناسم برېښنالیک',
    invalidPhone: 'ناسمه تلیفون شمېره',
    passwordTooShort: 'پټنوم ډېر لنډ دی',
    passwordsDoNotMatch: 'پټنومونه سره سمون نه لري',
  },
  success: {
    propertySaved: 'ملک په بریالیتوب سره خوندي شو',
    propertyDeleted: 'ملک په بریالیتوب سره ړنګ شو',
    propertyUpdated: 'ملک په بریالیتوب سره تازه شو',
    profileUpdated: 'پروفایل په بریالیتوب سره تازه شو',
    settingsSaved: 'تنظیمات په بریالیتوب سره خوندي شول',
  },
};
