export const pashto = {
  common: {
    continue: 'دوام ورکول',
    cancel: 'لغوه کول',
    save: 'خوندي کول',
    delete: 'ړنګول',
    edit: 'سمول',
    back: 'بیرته',
    next: 'راتلونکی',
    submit: 'سپارل',
    confirm: 'تایید',
    close: 'تړل',
    search: 'لټون',
    filter: 'فلټر',
    apply: 'پلي کول',
    reset: 'بیا تنظیمول',
    select: 'غوره کول',
    loading: 'لوډ کیږي...',
    error: 'تېروتنه',
    success: 'بریالیتوب',
    yes: 'هو',
    no: 'نه',
    ok: 'سمه ده',
    done: 'بشپړ',
    required: 'اړین',
    optional: 'اختیاري',
    all: 'ټول',
    more: 'نور',
    less: 'لږ',
    viewAll: 'ټول وګورئ',
    language: 'ژبه',
    changeLanguage: 'ژبه بدلول',
  },
  auth: {
    login: 'ننوتل',
    register: 'نوم لیکنه',
    logout: 'وتل',
    forgotPassword: 'پټنوم مو هیر شوی؟',
    resetPassword: 'پټنوم بیا تنظیمول',
    email: 'برېښنالیک',
    password: 'پټنوم',
    confirmPassword: 'پټنوم تایید',
    fullName: 'بشپړ نوم',
    phone: 'تلیفون شمېره',
    username: 'کارن نوم',
    welcomeBack: 'بیرته ښه راغلاست',
    createAccount: 'حساب جوړول',
    alreadyHaveAccount: 'حساب لرئ؟',
    dontHaveAccount: 'حساب نه لرئ؟',
    signIn: 'ننوتل',
    signUp: 'نوم لیکنه',
    enterEmail: 'خپل برېښنالیک دننه کړئ',
    enterPassword: 'خپل پټنوم دننه کړئ',
    enterPhone: 'خپله تلیفون شمېره دننه کړئ',
    enterOTP: 'تایید کوډ دننه کړئ',
    verifyOTP: 'کوډ تایید',
    resendOTP: 'کوډ بیا لیږل',
    otpSent: 'تایید کوډ واستول شو',
    invalidCredentials: 'ناسم معلومات',
    rememberMe: 'ما یاد ساتئ',
  },
  tabs: {
    home: 'کور',
    dashboard: 'ډشبورډ',
    properties: 'املاک',
    filters: 'فلټرونه',
    reset: 'بیا تنظیمول',
    people: 'خلک',
    profile: 'پروفایل',
    menus: 'مینو',
    add: 'اضافه کول',
    createProperty: 'ملک اضافه کول',
    insights: 'راپورونه',
  },
  welcome: {
    badge: 'خپله راتلونکې پته ومومئ',
    title: 'باوري املاک، د چټکو پرېکړو لپاره',
    subtitle: 'پریمیم لیستونه، پروژې او تایید شوي مشاورین په یوه اسانه تجربه کې وګورئ.',
    feature1Title: 'هوښیار ملک لټون',
    feature1Subtitle: 'د موقعیت، بودیجې او ملک ډول له مخې ژر فلټر وکړئ.',
    feature2Title: 'پروژې او ښارکونه',
    feature2Subtitle: 'برجونه، بازارونه او ښارکونه د حقیقي واحدونو له موجودیت سره وګورئ.',
    feature3Title: 'تایید شوې اړیکې',
    feature3Subtitle: 'له باوري مشاورینو سره مستقیم اړیکه ونیسئ او په ډاډ مخکې لاړ شئ.',
    getStarted: 'لټون پیل کړئ',
    signIn: 'ننوتل',
    exploreGuest: 'د مېلمه په توګه لټون',
  },
  property: {
    property: 'ملک',
    properties: 'املاک',
    myProperties: 'زما املاک',
    addProperty: 'ملک اضافه کول',
    editProperty: 'ملک سمول',
    deleteProperty: 'ملک ړنګول',
    propertyDetails: 'د ملک تفصیلات',
    propertyType: 'د ملک ډول',
    price: 'بیه',
    location: 'موقعیت',
    area: 'مساحت',
    bedrooms: 'خوب کوټې',
    bathrooms: 'تشناب',
    beds: 'خوب',
    baths: 'تشناب',
    sqft: 'مربع متر',
    forSale: 'د پلور لپاره',
    forRent: 'د کرایې لپاره',
    sale: 'پلور',
    rent: 'کرایه',
    sold: 'وپلورل شو',
    rented: 'په کرایه ورکړل شو',
    available: 'شته',
    unavailable: 'نشته',
    featured: 'ځانګړی',
    new: 'نوی',
    popular: 'مشهور',
    recommended: 'وړاندیز شوی',
    nearby: 'نږدې',
    viewProperty: 'ملک وګورئ',
    contactAgent: 'له مشاور سره اړیکه',
    shareProperty: 'ملک شریک کړئ',
    saveProperty: 'ملک خوندي کړئ',
    favorites: 'خوښې',
    noProperties: 'هیڅ ملک و نه موندل شو',
    house: 'کور',
    apartment: 'اپارتمان',
    shop: 'دکان',
    office: 'دفتر',
    land: 'ځمکه',
    plot: 'پلاټ',
    tower: 'برج',
    towers: 'برجونه',
    market: 'بازار',
    markets: 'بازارونه',
    sharak: 'شهرک',
    sharaks: 'شهرکونه',
    building: 'ودانۍ',
    units: 'واحدونه',
    floor: 'پوړ',
    unitNumber: 'د واحد شمېره',
    totalFloors: 'ټول پوړونه',
    amenities: 'اسانتیاوې',
    description: 'تشریح',
    title: 'عنوان',
    address: 'پته',
    priceOnRequest: 'بیه د غوښتنې پر بنسټ',
    parking: 'پارکینګ',
    securityGuard: 'امنیتي ساتونکی',
    centralHeatingSystem: 'مرکزي تودوخې سیستم',
    cupboards: 'المارۍ',
    sunny: 'لمر ګیر',
    basement: 'تهخانه',
    ac: 'تودوخې/یخنۍ',
    lift: 'لفټ',
    furnished: 'فرنیچر شوی',
    semiFurnished: 'نیمایی فرنیچر شوی',
    solarFacility: 'لمریز اسانتیا',
    generatorFacility: 'جنراتور اسانتیا',
    electricity: 'برېښنا',
    waterSupply: 'د اوبو رسونه',
    internet: 'انټرنېټ',
    gym: 'ورزشي جم',
    pool: 'د لامبو حوض',
    garden: 'باغچه',
    gas: 'ګاز',
    perMonth: '/ میاشت',
    active: 'فعال',
    deActive: 'غیر فعال',
    planned: 'پلان شوی',
    added: 'اضافه شوی',
    locatedIn: 'موقعیت په',
    verifiedAgent: 'تایید شوی مشاور',
    propertyOwner: 'د ملک مالک',
    sqFt: 'مربع فوټ',
    bath: 'تشناب',
    bed: 'خوب',
    unitsAvailableIn: 'په دې کې شته واحدونه',
    container: 'کانټینر',
    addUnit: 'واحد اضافه کول',
    noHomesAvailable: 'تر اوسه کوم کور شتون نلري',
    propertyDescription: 'د ملک تشریح',
    openInMaps: 'په نقشه کې خلاصول',
    tapToExpand: 'د لویولو لپاره کلیک وکړئ',
    mapNotAvailable: 'د نقشې موقعیت شتون نلري',
    propertyInformation: 'د ملک معلومات',
    propertyCode: 'د ملک کوډ',
    ownerName: 'د مالک نوم',
    copied: 'کاپي شو',
    propertyCodeCopied: 'د ملک کوډ {code} کلیپ بورډ ته کاپي شو',
    deletePropertyTitle: 'ملک ړنګول',
    deletePropertyMessage: 'دا عمل د بیرته راګرځولو وړ نه دی. ایا تاسو ډاډه یاست؟',
    failedToDelete: 'ملک ړنګول ناکام شو',
    propertyNotFound: 'ملک و نه موندل شو',
    returnToBrowse: 'لټون ته بیرته',
    transaction: 'معامله',
    sendInquiry: 'پوښتنه لیږل',
    inquirySent: 'پوښتنه واستول شوه',
    inquiryRecorded: 'ستاسو په دې ملک کې علاقه ثبت شوه.',
    whatsappNotInstalled: 'واټساپ ستاسو په وسیله کې نصب نه دی',
    unableToOpenVideo: 'دا ویډیو خلاصولی نه شو',
    locationNotSpecified: 'موقعیت مشخص شوی نه دی',
    shopNo: 'د دکان شمېره',
    officeNo: 'د دفتر شمېره',
    apartmentNo: 'د اپارتمان شمېره',
    featuresTab: 'ځانګړنې',
    availableHomes: 'شتون لرونکي کورونه',
    allProperties: 'ټول ملکیتونه',
    about: 'په اړه',
    noDescriptionAvailable: 'تشریح شتون نه لري.',
    facilities: 'اسانتیاوې',
    agentInformation: 'د اجنټ معلومات',
    tapToViewProfile: 'د پروفایل لیدو لپاره ټچ کړئ',
    showing: 'ښودل کیږي',
    availableHomesLower: 'شتون لرونکي کورونه',
    propertiesAddedByAgent: 'د اجنټ لخوا زیات شوي ملکیتونه',
    propertyTypeUpper: 'د ملکیت ډول',
    bedroomsUpper: 'د خوب خونې',
    allBeds: 'ټولې خونې',
    others: 'نور',
    noAvailableHomesFound: 'هیڅ شتون لرونکی کور ونه موندل شو.',
    noPropertiesAddedByAgent: 'تر اوسه د دې اجنټ لخوا کوم ملکیت نه دی زیات شوی.',
    addShopOffice: 'دوکان/دفتر زیات کړئ',
    addApartmentShopOfficeLandPlotHouse: 'اپارتمان/دوکان/دفتر/ځمکه/پلاټ/کور زیات کړئ',
    addApartmentShopOffice: 'اپارتمان/دوکان/دفتر زیات کړئ',
  },
  filters: {
    filters: 'فلټرونه',
    applyFilters: 'فلټرونه پلي کول',
    clearFilters: 'فلټرونه پاکول',
    propertyType: 'د ملک ډول',
    priceRange: 'د بیې حد',
    minPrice: 'لږترلږه بیه',
    maxPrice: 'ډېره بیه',
    min: 'لږترلږه',
    max: 'ډېره',
    location: 'موقعیت',
    bedrooms: 'خوب کوټې',
    bathrooms: 'تشناب',
    area: 'مساحت',
    status: 'حالت',
    sortBy: 'ترتیبول',
    newest: 'تازه',
    oldest: 'زوړ',
    priceLowToHigh: 'بیه: ټیټه نه لوړه',
    priceHighToLow: 'بیه: لوړه نه ټیټه',
    province: 'ولایت',
    district: 'ولسوالۍ',
    districtIn: 'ولسوالۍ په',
    areaLocation: 'ساحه',
    areaIn: 'ساحه په',
    category: 'کټګوري',
    purpose: 'موخه',
    agent: 'مشاور',
    priceRangeRent: 'د بیې حد (کرایه)',
    priceRangeSale: 'د بیې حد (پلور)',
    searching: 'لټون کیږي...',
    searchProperties: 'املاک لټول',
  },
  profile: {
    profile: 'پروفایل',
    myProfile: 'زما پروفایل',
    editProfile: 'پروفایل سمول',
    myTowers: 'زما برجونه',
    myMarkets: 'زما بازارونه',
    mySharaks: 'زما شهرکونه',
    settings: 'تنظیمات',
    help: 'مرسته',
    about: 'په اړه',
    termsAndConditions: 'شرایط او ضوابط',
    privacyPolicy: 'د محرمیت پالیسي',
    contactUs: 'له موږ سره اړیکه',
    rateApp: 'اپلیکیشن ته نمرې ورکړئ',
    shareApp: 'اپلیکیشن شریک کړئ',
    version: 'نسخه',
    accountSettings: 'د حساب تنظیمات',
    notifications: 'خبرتیاوې',
    language: 'ژبه',
    darkMode: 'تیاره حالت',
    myFavorites: 'زما خوښې',
    savedSearches: 'خوندي شوي لټونونه',
    recentlyViewed: 'پخوا لیدل شوي',
  },
  dashboard: {
    welcome: 'ښه راغلاست',
    hello: 'سلام',
    recentProperties: 'وروستي املاک',
    featuredProperties: 'ځانګړي املاک',
    popularProperties: 'مشهور املاک',
    stats: 'احصائیې',
    totalProperties: 'ټول املاک',
    totalAgents: 'ټول مشاورین',
    totalDeals: 'ټولې معاملې',
    quickActions: 'ګړندي اقدامات',
    adminConsole: 'د ادمین کنسول',
    systemStatus: 'د سیستم حالت: فعال',
    users: 'کاروونکي',
    agents: 'مشاورین',
    globalStatistics: 'عمومي احصائیې',
    activeDeals: 'فعالې معاملې',
    managementTools: 'د مدیریت وسیلې',
    rolesPermissions: 'رولونه او اجازې',
    reviewAllListings: 'ټول لیستونه وګورئ',
    analyzeGrowth: 'وده تحلیل کړئ',
    systemPlatform: 'د سیستم پلیټ فارم',
    towers: 'د ښار منظرې برجونه',
    markets: 'فعال سوداګریز بازارونه',
    sharaks: 'لوکس استوګنیز ښارکونه',
    loadingContent: 'مینځپانګه بار کیږي...',
    signInPrompt: 'خپل املاکو حساب ته ننوځئ',
  },
  people: {
    people: 'خلک',
    agents: 'مشاورین',
    owners: 'مالکان',
    clients: 'پیرودونکي',
    contactInfo: 'د اړیکې معلومات',
    propertiesListed: 'ثبت شوي املاک',
    viewProfile: 'پروفایل وګورئ',
  },
  deals: {
    deals: 'معاملې',
    myDeals: 'زما معاملې',
    createDeal: 'معامله جوړول',
    viewDeal: 'معامله وګورئ',
    dealDetails: 'د معاملې تفصیلات',
    dealStatus: 'د معاملې حالت',
    pending: 'په انتظار کې',
    active: 'فعال',
    completed: 'بشپړ شوی',
    cancelled: 'لغوه شوی',
  },
  errors: {
    somethingWentWrong: 'یوه ستونزه رامنځته شوه',
    tryAgain: 'بیا هڅه وکړئ',
    networkError: 'د شبکې تېروتنه',
    invalidInput: 'ناسم معلومات',
    requiredField: 'دا برخه اړینه ده',
    invalidEmail: 'ناسم برېښنالیک',
    invalidPhone: 'ناسمه تلیفون شمېره',
    passwordTooShort: 'پټنوم ډېر لنډ دی',
    passwordValid: 'پټنوم شرطونه پوره کوي',
    passwordsMatch: 'پټنومونه سره سمون لري',
    passwordsDoNotMatch: 'پټنومونه سره سمون نه لري',
  },
  success: {
    propertySaved: 'ملک په بریالیتوب سره خوندي شو',
    propertyDeleted: 'ملک په بریالیتوب سره ړنګ شو',
    propertyUpdated: 'ملک په بریالیتوب سره تازه شو',
    profileUpdated: 'پروفایل په بریالیتوب سره تازه شو',
    settingsSaved: 'تنظیمات په بریالیتوب سره خوندي شول',
  },
};
