const PERMISSIONS = {
    ADD_PROPERTY: 'ADD_PROPERTY',
    MY_PROPERTIES: 'MY_PROPERTIES',
    MY_TOWERS: 'MY_TOWERS',
    MY_MARKETS: 'MY_MARKETS',
    MY_SHARAKS: 'MY_SHARAKS',
    TRANSACTION_HISTORY: 'TRANSACTION_HISTORY',
};

const PERMISSION_DISPLAY_NAMES = {
    [PERMISSIONS.ADD_PROPERTY]: 'Add Property',
    [PERMISSIONS.MY_PROPERTIES]: 'My Properties',
    [PERMISSIONS.MY_TOWERS]: 'My Towers',
    [PERMISSIONS.MY_MARKETS]: 'My Markets',
    [PERMISSIONS.MY_SHARAKS]: 'My Sharaks',
    [PERMISSIONS.TRANSACTION_HISTORY]: 'Transaction History',
};

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

module.exports = { PERMISSIONS, PERMISSION_DISPLAY_NAMES, ALL_PERMISSIONS };
